version: '3.0'

services:
  main:
    container_name: backend
    build:
      context: .
    volumes:
      - ./src:/app
    ports:
      - 5000:5000
      - 9229:9229
    command: npm run start
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: postgres
    image: postgres:12
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:

